on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.PAT }}

    - uses: cachix/cachix-action@v16
      with:
        name: crolbar
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build
    - run: nix shell --command sh -c "echo OK"
